<!DOCTYPE html>
<html lang="zh-tw">
<head>
	<title>新增輪播圖片 | BeautyNose管理後台</title>
	<?php $this->partial('shared/include');?>
</head>
<body>
	<?php $this->partial('shared/nav');?>
	<?php $this->partial('shared/sidebar');?>
	<div class="col-sm-9 col-sm-offset-3 col-lg-10 col-lg-offset-2 main">			
		<div class="row">
			<ol class="breadcrumb">
				<li><a href="#"><svg class="glyph stroked home"><use xlink:href="#stroked-home"></use></svg></a></li>
				<li class="active">輪播圖片</li>
				<li class="active">新增</li>
			</ol>
		</div><!--/.row-->
		
		<div class="row">
			<div class="col-md-12">
				<div class="panel panel-default">
					<div class="panel-heading">新增</div>
					<div class="panel-body">
						<div class="col-md-8">
						<?php echo $this->tag->form(array('banner/add', 'enctype' => 'multipart/form-data')); ?>
							<?php $this->flashSession->output(true);?>
							<div class="form-group">
							    <label class="col-sm-3 control-label">標題*</label>
							    <div class="col-sm-9">
							      <input class="form-control" name="title" type="text" placeholder="請輸入標題" required>
							    </div>
							</div>
							<div class="form-group">
							    <label class="col-sm-3 control-label">排序*</label>
							    <div class="col-sm-9">
							      <input class="form-control" name="sort" type="text" placeholder="請輸入排序" required value="10">
							      <span class="help-block">數字越小越前</span>
							    </div>
							</div>
							<div class="form-group">
							    <label class="col-sm-3 control-label">圖片*</label>
							    <div class="col-sm-9">
							      <input class="form-control" name="photo" type="file" placeholder="請上傳圖片" required>
							      <span class="help-block">請上傳 800x500 以上的圖片</span>
							    </div>
							</div>
							<div class="form-group">
							    <label class="col-sm-3 control-label">連結網址類型*</label>
							    <div class="col-sm-9">
							    	<div class="radio">
									  <label><input type="radio" name="type" value="" checked="checked">沒有網址</label>
									</div>
									<div class="radio">
									  <label><input type="radio" name="type" value="linkto">本站</label>
									</div>
									<div class="radio">
									  <label><input type="radio" name="type" value="other">另開新頁</label>
									</div>
							      <span class="help-block">不需要連結網址請選「沒有網址」</span>
							    </div>
							</div>
							<div class="form-group other-area" style="display: none;">
							    <label class="col-sm-3 control-label">連結網址</label>
							    <div class="col-sm-9">
							      <input class="form-control" type="text" name="other" value="" placeholder="連結網址">
							    </div>
							</div>
							<div class="form-group linkto-area" style="display: none;">
							    <label class="col-sm-3 control-label">連結區塊</label>
							    <div class="col-sm-9">
								    <select class="form-control" name="linkto">
								    	<option value="#case">美麗見證</option>
								    	<option value="#about">什麼是卡麥拉</option>
								    	<option value="#qa">美鼻Q&A</option>
								    	<option value="#media">媒體報導</option>
								    	<option value="#activity">活動紀實</option>
								    	<option value="#contact">聯絡我們</option>
								    </select>
							    </div>
							</div>
							<script type="text/javascript">
								$('input[name=type]').change(function() {
									switch(this.value) {
										case '' :
											$('.other-area').hide();
											$('.linkto-area').hide();
										break;
										case 'linkto' :
											$('.other-area').hide();
											$('.linkto-area').show();
										break;
										case 'other' :
											$('.other-area').show();
											$('.linkto-area').hide();
										break;
									}
							    });
							</script>
	  						<button type="submit" class="btn btn-primary btn-sm" type="submit">送出</button>
	  						<input type="hidden" name="return_to" value="<?php echo $return_to; ?>"/>
            				<input type="hidden" name="<?php echo $this->security->getTokenKey() ?>" value="<?php echo $this->security->getToken() ?>"/>
						</div>
						<?php echo $this->tag->endForm();?>
					</div>
				</div>
			</div>
		</div>
	</div>	<!--/.main-->
</body>
</html>