<!DOCTYPE html>
<html lang="zh-tw">
<head>
	<title>編輯美麗見證 | BeautyNose管理後台</title>
	<?php $this->partial('shared/include');?>
</head>
<body>
	<?php $this->partial('shared/nav');?>
	<?php $this->partial('shared/sidebar');?>
	<div class="col-sm-9 col-sm-offset-3 col-lg-10 col-lg-offset-2 main">			
		<div class="row">
			<ol class="breadcrumb">
				<li><a href="#"><svg class="glyph stroked home"><use xlink:href="#stroked-home"></use></svg></a></li>
				<li class="active">美麗見證</li>
				<li class="active">編輯</li>
			</ol>
		</div><!--/.row-->
		
		<div class="row">
			<div class="col-md-12">
				<div class="panel panel-default">
					<div class="panel-heading">編輯</div>
					<div class="panel-body">
						<div class="col-md-8">
						<?php echo $this->tag->form(array('case/edit/'. $id, 'enctype' => 'multipart/form-data')); ?>
							<?php $this->flashSession->output(true);?>
							<div class="form-group">
							    <label class="col-sm-3 control-label">標題*</label>
							    <div class="col-sm-9">
							      <input class="form-control" name="title" type="text" placeholder="請輸入標題" value="<?php echo (!empty($data->title)) ? $data->title : '';?>" required>
							    </div>
							</div>
							<div class="form-group">
							    <label class="col-sm-3 control-label">摘要</label>
							    <div class="col-sm-9">
							      <input class="form-control" name="summary" type="text" placeholder="請輸入摘要" value="<?php echo (!empty($data->summary)) ? $data->summary : '';?>">
							    </div>
							</div>
							<div class="form-group">
							    <label class="col-sm-3 control-label">排序*</label>
							    <div class="col-sm-9">
							      <input class="form-control" name="sort" type="text" placeholder="請輸入排序" value="<?php echo (!empty($data->sort)) ? $data->sort : '';?>" required>
							      <span class="help-block">數字越小越前</span>
							    </div>
							</div>
							<div class="form-group">
							    <label class="col-sm-3 control-label">圖片*</label>
							    <div class="col-sm-9">
							      <img style="width: 100%;" src="<?php echo $data->photo;?>">
							      <input class="form-control" name="photo" type="file" placeholder="請上傳圖片">
							      <span class="help-block">請上傳 800x500 以上的圖片</span>
							    </div>
							</div>
							<div class="form-group">
							    <label class="col-sm-3 control-label">連結網址</label>
							    <div class="col-sm-9">
							      <input class="form-control" type="text" name="url" placeholder="連結網址" value="<?php echo (!empty($data->url)) ? $data->url : '';?>">
							      <span class="help-block">不需要連結請留空</span>
							    </div>
							</div>
	  						<button type="submit" class="btn btn-primary btn-sm" type="submit">送出</button>
	  						<input type="hidden" name="return_to" value="<?php echo $return_to; ?>"/>
	  						 <input type="hidden" name="id" value="<?php echo $id; ?>"/>
            				<input type="hidden" name="<?php echo $this->security->getTokenKey() ?>" value="<?php echo $this->security->getToken() ?>"/>
						</div>
						<?php echo $this->tag->endForm();?>
					</div>
				</div>
			</div>
		</div>
	</div>	<!--/.main-->
</body>
</html>