<meta charset="utf-8">
<title>ESWT 管理系統</title>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1">
<link href="/css/bootstrap.min.css" rel="stylesheet">
<link href="/css/styles.css" rel="stylesheet">
<link href="/css/custom.css" rel="stylesheet">
<script src="/js/lumino.glyphs.js"></script>
<!--[if lt IE 9]>
<script src="/js/html5shiv.js"></script>
<script src="/js/respond.min.js"></script>
<![endif]-->
<script type="text/javascript" src="/js/jquery-2.2.3.min.js"></script>
<script type="text/javascript" src="/js/jquery.cookie.js"></script>
<script type="text/javascript" src="/js/moment.min.js"></script>
<script type="text/javascript" src="/js/moment-with-locales.js"></script>
<script type="text/javascript" src="/js/mustache-2.1.3.min.js"></script>
<script src="/js/bootstrap.min.js"></script>
<script src="/js/chart.min.js"></script>
<!-- <script src="/js/chart-data.js"></script> -->
<!-- <script src="/js/easypiechart.js"></script> -->
<!-- <script src="/js/easypiechart-data.js"></script> -->
<script src="/js/bootstrap-datetimepicker.js"></script>	
<script src="/js/jquery.twzipcode.min.js"></script>	
