<!DOCTYPE html>
<html lang="zh-tw">
<head>
	<title>表單資料列表 | BeautyNose管理後台</title>
	<?php $this->partial('shared/include');?>
</head>
<body>
	<?php $this->partial('shared/nav');?>
	<?php $this->partial('shared/sidebar');?>
	<div class="col-sm-9 col-sm-offset-3 col-lg-10 col-lg-offset-2 main">
		<div class="row">
			<ol class="breadcrumb">
				<li><a href="#"><svg class="glyph stroked home"><use xlink:href="#stroked-home"></use></svg></a></li>
				<li class="active">表單資料</li>
				<li class="active">列表</li>
			</ol>
		</div><!--/.row-->
		<div class="row">
			<div class="col-md-12">
				<div class="panel panel-default">
					<div class="panel-heading">列表</div>
					<div class="panel-body">
						<table class="table table-hover">
						    <thead><tr>
						    	<th width="5%;">流水號</th>
						    	<th width="15%;">姓名 <br> Facebook 暱稱</th>
						    	<th width="25%;">手機 <br> 地址 <br> Email</th>
						    	<th width="25%;">問題</th>
						    	<th width="20%;">照片</th>
						    	<th width="10%;">日期</th>
						    </tr></thead>
							<tbody>
								<?php foreach($data as $k => $row):
								$no = $k+1; ?>
									<tr>
										<td><?php echo $no; ?></td>
										<td><?php echo $row->name . '<br>' . $row->facebook_nickname;?></td>
										<td>
											<?php echo $row->mobile . '<br>' . $row->address . '<br>' . $row->email;?></td>
										<td><?php echo $row->message;?></td>
										<td>
											<?php if($row->photo !== "") :?>
											<img src="<?php echo $row->photo;?>" style="width:100%;">
											<a href="<?php echo $row->photo;?>" download="<?php echo $row->name . '-' . $row->create;?>">儲存照片</a>
											<?php else :?>
												沒有照片
											<?php endif;?>
										</td>
										<td><?php echo (empty($row->create)) ? "-" : $row->create;?></td>
									</tr>
								<?php endforeach;?>
							</tbody>
						</table>
					</div>
				</div>
			</div>
		</div>
	</div>	<!--/.main-->
</body>
</html>