<!DOCTYPE html>
<html lang="zh-tw">
<head>
	<title>首頁 | BeautyNose管理後台</title>
	<?php $this->partial('shared/include');?>
</head>
<body>
	<?php $this->partial('shared/nav');?>
	<?php $this->partial('shared/sidebar');?>
	<div class="col-sm-9 col-sm-offset-3 col-lg-10 col-lg-offset-2 main">			
		<div class="row">
			<ol class="breadcrumb">
				<li><a href="#"><svg class="glyph stroked home"><use xlink:href="#stroked-home"></use></svg></a></li>
				<li class="active">首頁</li>
			</ol>
		</div>
		<!--
		TODO
		-->
	</div>
</body>
</html>